# Config Yaml.
# 
# Info.
# Both `decrypt` and `encrypt` are an array of objects.
# Each element in array is an object with two sub fields: 
# - src : specify a path to a source file you want to decrypt/encrypt.
# - out : specify a path where the encrypted/decrypted file should be written to.
#
# Leave decrypt/encrypt field as an empty array to skip the enc/dec task.

# Enqueue following files for decrypt.
decrypt: 
  - src: 'C:\Projects\playground\test.txt'
    out: 'C:\Projects\playground\dec-test.txt'
   # Ver - 000 (invalid)
  - src: 'C:\Projects\playground\ver000-armorgrp.dat'
    out: 'C:\Projects\playground\dec-ver000-armorgrp.dat'
    # Ver - 111
  - src: 'C:\Projects\playground\ver111-editor.u'
    out: 'C:\Projects\playground\dec-ver111-editor.u'
    # Ver - 121 
  - src: 'C:\Projects\playground\ver121-dropItemsTex.utx'
    out: 'C:\Projects\playground\dec-ver121-dropItemsTex.utx'
    # Ver - 413
  - src: 'C:\Projects\playground\ver413-armorgrp.dat'
    out: 'C:\Projects\playground\dec-ver413-armorgrp.dat'

# Enqueue following files for encrypt.
encrypt: 
  # Ver - 111
  - src: 'C:\Projects\playground\ver111-editor.u'
    out: 'C:\Projects\playground\dec-ver111-editor.u'